### ISSUE TITLE
Update Design Documentation

### ISSUE THREAD

**Issue by heobu** [8hk/AEK#31] opened 2020-11-30 18:39 UTC
Based on the feedback we received, all design documentation should be updated:

- [ ] Mockups
- [ ] Use case diagram
- [ ] Class diagram
- [ ] Sequence diagrams

**Comment by 8hk** [comment] 2020-11-30 20:17
Duplicate of #32 , #33 , #34 , #35

**Closed as completed by 8hk** 2020-11-30 20:17 UTC
Labels: documentation, design
